services:
  - type: web
    name: kashy-finance
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --chdir src 'app:create_app()'"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
